# BMB 2026-04-14
# Centralized country name → ISO A3 lookup table (tribble). Source this in R scripts
# that need country normalization. See also country_mapping.py for Python.

country_iso_mapping <- tribble(
  ~country_clean, ~iso_a3,
  # Americas
  "canada", "CAN",
  "canada western", "CAN",
  "western canada", "CAN",
  "eastern canada", "CAN",
  "united states", "USA",
  "mexico", "MEX",
  "guatemala", "GTM",
  "belize", "BLZ",
  "honduras", "HND",
  "el salvador", "SLV",
  "nicaragua", "NIC",
  "costa rica", "CRI",
  "panama", "PAN",
  "colombia", "COL",
  "antioquia", "COL",
  "venezuela", "VEN",
  "guyana", "GUY",
  "suriname", "SUR",
  "french guiana", "GUF",
  "argentina", "ARG",
  "new caledonia", "NCL",
  "brazil", "BRA",
  "chile", "CHL",
  "southern chile", "CHL",
  "peru", "PER",
  "ecuador", "ECU",
  "paraguay", "PRY",
  "uruguay", "URY",
  "bolivia", "BOL",
  "jamaica", "JAM",
  "dominican republic", "DOM",
  "haiti", "HTI",
  "cuba", "CUB",
  "puerto rico", "PRI",
  "trinidad and tobago", "TTO",
  "bahamas", "BHS",
  "barbados", "BRB",
  "grenada", "GRD",
  "saint lucia", "LCA",
  "saint vincent and the grenadines", "VCT",
  "antigua and barb.", "ATG",
  "antigua and barbuda", "ATG",
  "dominica", "DMA",
  "saint kitts and nevis", "KNA",
  "nova scotia", "CAN",
  "british columbia", "CAN",
  "viçosa", "BRA",
  "eastern canada", "CAN",
  "new brunswick", "CAN",
  # Europe
  "united kingdom", "GBR",
  "ireland", "IRL",
  "france", "FRA",
  "germany", "DEU",
  "italy", "ITA",
  "sicily", "ITA",
  "sardinia", "ITA",
  "lombardy", "ITA",
  "tuscany", "ITA",
  "spain", "ESP",
  "canary", "ESP",
  "portugal", "PRT",
  "netherlands", "NLD",
  "belgium", "BEL",
  "luxembourg", "LUX",
  "switzerland", "CHE",
  "swiss jura mountains", "CHE",
  "austria", "AUT",
  "czech republic", "CZE",
  "slovakia", "SVK",
  "slovenia", "SVN",
  "croatia", "HRV",
  "bosnia and herzegovina", "BIH",
  "serbia", "SRB",
  "montenegro", "MNE",
  "macedonia", "MKD",
  "kosovo", "XKX",
  "albania", "ALB",
  "greece", "GRC",
  "romania", "ROU",
  "malta", "MLT",
  "bulgaria", "BGR",
  "hungary", "HUN",
  "poland", "POL",
  "ukraine", "UKR",
  "belarus", "BLR",
  "russia", "RUS",
  "russian far east", "RUS",
  "moldova", "MDA",
  "latvia", "LVA",
  "lithuania", "LTU",
  "estonia", "EST",
  "denmark", "DNK",
  "sweden", "SWE",
  "norway", "NOR",
  "finland", "FIN",
  "iceland", "ISL",
  "northern ireland", "GBR",
  "scotland", "GBR",
  "wales", "GBR",
  "england", "GBR",
  "britain", "GBR",
  "the netherlands", "NLD",
  "svalbard", "NOR",
  "greenland", "GRL",
  "faroe", "FRO",
  "faroe islands", "FRO",
  "great britain", "GBR",
  "gomera", "ESP",
  # Africa
  "egypt", "EGY",
  "benin", "BEN",
  "libya", "LBY",
  "algeria", "DZA",
  "tamanghasset", "DZA",
  "tunisia", "TUN",
  "msila", "DZA",
  "el-haourane", "DZA",
  "morocco", "MAR",
  "south africa", "ZAF",
  "transkei", "ZAF",
  "southern transkei", "ZAF",
  "namibia", "NAM",
  "botswana", "BWA",
  "zimbabwe", "ZWE",
  "zambia", "ZMB",
  "malawi", "MWI",
  "mozambique", "MOZ",
  "tanzania", "TZA",
  "kenya", "KEN",
  "uganda", "UGA",
  "rwanda", "RWA",
  "burundi", "BDI",
  "congo", "COG",
  "democratic republic of congo", "COD",
  "cameroon", "CMR",
  "central african republic", "CAF",
  "gabon", "GAB",
  "equatorial guinea", "GNQ",
  "nigeria", "NGA",
  "niger", "NER",
  "ghana", "GHA",
  "ivory coast", "CIV",
  "côte d'ivoire", "CIV",
  "burkina faso", "BFA",
  "mali", "MLI",
  "mauritania", "MRT",
  "senegal", "SEN",
  "gambia", "GMB",
  "guinea-bissau", "GNB",
  "guinea", "GIN",
  "sierra leone", "SLE",
  "liberia", "LBR",
  "ethiopia", "ETH",
  "somalia", "SOM",
  "djibouti", "DJI",
  "eritrea", "ERI",
  "sudan", "SDN",
  "south sudan", "SSD",
  "chad", "TCD",
  "mauritius", "MUS",
  "madagascar", "MDG",
  "seychelles", "SYC",
  # Asia
  "china", "CHN",
  "anhui huoshan", "CHN",
  "of yunnan", "CHN",
  "anhui", "CHN",
  "southwestern china", "CHN",
  "qinghai-tibet plateau", "CHN",
  "qinghai-tibet", "CHN",
  "qinghai tibet", "CHN",
  "north china", "CHN",
  "south china", "CHN",
  "east china", "CHN",
  "west china", "CHN",
  "southern china", "CHN",
  "southeast china", "CHN",
  "southwest china", "CHN",
  "people's republic of china", "CHN",
  "peoples republic of china", "CHN",
  "prc", "CHN",
  "trinidad", "TTO",
  "trinidad and tobago", "TTO",
  "pr china", "CHN",
  "p r china", "CHN",
  "taiwan", "TWN",
  "formosa", "TWN",
  "formosan", "TWN",
  "hong kong", "HKG",
  "macau", "MAC",
  "japan", "JPN",
  "south korea", "KOR",
  "korea", "KOR",
  "north korea", "PRK",
  "mongolia", "MNG",
  "afghanistan", "AFG",
  "pakistan", "PAK",
  "india", "IND",
  "chhattisgarh", "IND",
  "central india", "IND",
  "arunachal pradesh", "IND",
  "tripura", "IND",
  "south east india", "IND",
  "north-east india", "IND",
  "northeast india", "IND",
  "bangladesh", "BGD",
  "nepal", "NPL",
  "bhutan", "BTN",
  "sri lanka", "LKA",
  "myanmar", "MMR",
  "thailand", "THA",
  "northern thailand", "THA",
  "thai", "THA",
  "laos", "LAO",
  "cambodia", "KHM",
  "vietnam", "VNM",
  "philippines", "PHL",
  "indonesia", "IDN",
  "malaysia", "MYS",
  "west malaysia", "MYS",
  "peninsular malaysia", "MYS",
  "singapore", "SGP",
  "brunei", "BRN",
  "brunei darussalam", "BRN",
  "east timor", "TLS",
  "timor-leste", "TLS",
  "papua new guinea", "PNG",
  "yemen", "YEM",
  "oman", "OMN",
  "united arab emirates", "ARE",
  "qatar", "QAT",
  "bahrain", "BHR",
  "kuwait", "KWT",
  "saudi arabia", "SAU",
  "saudi-arabia", "SAU",
  "iraq", "IRQ",
  "iran", "IRN",
  "turkey", "TUR",
  "türkiye", "TUR",
  "syria", "SYR",
  "lebanon", "LBN",
  "israel", "ISR",
  "palestine", "PSE",
  "cyprus", "CYP",
  "kazakhstan", "KAZ",
  "uzbekistan", "UZB",
  "turkmenistan", "TKM",
  "tajikistan", "TJK",
  "kyrgyzstan", "KGZ",
  # Oceania & Pacific
  "australia", "AUS",
  "new zealand", "NZL",
  "aotearoa", "NZL",
  "fiji", "FJI",
  "samoa", "WSM",
  "vanuatu", "VUT",
  "solomon islands", "SLB",
  "micronesia", "FSM",
  "palau", "PLW",
  "marshall islands", "MHL",
  "kiribati", "KIR",
  "tuvalu", "TUV",
  "nauru", "NRU",
  "new south wales", "AUS",
  # Regions & Provinces
  "yunnan", "CHN",
  "qinghai", "CHN",
  "jiangxi", "CHN",
  "gansu", "CHN",
  "nei mongol", "CHN",
  "inner mongolia", "CHN",
  "sichuan", "CHN",
  "hainan", "CHN",
  "xinjiang", "CHN",
  "zhejiang", "CHN",
  "xuwen", "CHN",
  "guangdong", "CHN",
  "fujian", "CHN",
  "guangxi", "CHN",
  "beijing", "CHN",
  "shanghai", "CHN",
  "liaoning", "CHN",
  "jilin", "CHN",
  "heilongjiang", "CHN",
  "tibet", "CHN",
  "fuyang", "CHN",
  "guizhou", "CHN",
  "zhanjiang", "CHN",
  "sumatra", "IDN",
  "java", "IDN",
  "borneo", "IDN",
  "jeddah", "SAU",
  "goa", "IND",
  "west bengal", "IND",
  "tamil nadu", "IND",
  "tamil naidu", "IND",
  "chennai", "IND",
  "mandi district", "IND",
  "himachal pradesh", "IND",
  "nashik", "IND",
  "himalaya", "IND",
  "rajasthan", "IND",
  "mumbai", "IND",
  "delhi", "IND",
  "new delhi", "IND",
  "bangalore", "IND",
  "hyderabad", "IND",
  "tamilnadu", "IND",
  "karnataka", "IND",
  "haryana", "IND",
  "uttarakhand", "IND",
  "uttarpradesh", "IND",
  "odisha", "IND",
  "manipur", "IND",
  "salem", "IND",
  "yercaud", "IND",
  "yercaud hills", "IND",
  "nashik district", "IND",
  "maharashtra", "IND",
  "assam", "IND",
  "kerala", "IND",
  "punjab", "IND",
  "uttar pradesh", "IND",
  "andhra pradesh", "IND",
  "andhra", "IND",
  "bombay", "IND",
  "telangana", "IND",
  "bengkulu", "IDN",
  "southern india", "IND",
  "meghalaya", "IND",
  "ne india", "IND",
  "northeastern india", "IND",
  "northern india", "IND",
  "northwestern india", "IND",
  "northeast india", "IND",
  "gujarati", "IND",
  "garhwal", "IND",
  "haridwar", "IND",
  "jammu kashmir", "IND",
  "khammam", "IND",
  "kodiyakarai", "IND",
  "kollam", "IND",
  "mandi", "IND",
  "mymensingh", "IND",
  "puducherry", "IND",
  "uttrakhand", "IND",
  "tamilnadu state", "IND",
  "karnataka state", "IND",
  "kalimantan", "IDN",
  "sulawesi", "IDN",
  "sarawak", "MYS",
  "johor", "MYS",
  "penang", "MYS",
  "peninsular malaysia", "MYS",
  "bahia state", "BRA",
  "minas gerais", "BRA",
  "sao paulo", "BRA",
  "rio grande do sul state", "BRA",
  "santa catarina state", "BRA",
  # Other locations
  "corsica", "FRA",
  "madeira", "PRT",
  "la reunion", "FRA",
  "martinique", "MTQ",
  "tahiti", "PYF",
  "moorea", "PYF",
  "tenerife", "ESP",
  "la palma", "ESP",
  "majorca", "ESP",
  "balearic", "ESP",
  "alicante", "ESP",
  "palencia", "ESP",
  "samsun", "TUR",
  "hormozgan", "IRN",
  "qena governorate", "EGY",
  "upper egypt", "EGY",
  "azerbaijan", "AZE",
  "primorsky", "RUS",
  "moscow oblast", "RUS",
  "amur", "RUS",
  "belorussian ssr", "BLR",
  "republic of moldova", "MDA",
  "shetland", "GBR",
  "shetlands", "GBR",
  "isle of man", "GBR",
  "flanders", "BEL",
  "alentejo", "PRT",
  "lisbon", "PRT",
  "tashkent", "UZB",
  "ulsan city", "KOR",
  "ibaraki", "JPN",
  "satakunta", "FIN",
  "ny-ålesund", "NOR",
  "spitsbergen", "NOR",
  "togo", "TGO",
  "comoros", "COM",
  "timor", "TLS",
  "timor leste", "TLS",
  "papua", "PNG",
  "falkland islands", "FLK",
  "ny aalesund", "NOR",
  "american samoa", "USA",
  "hawaii", "USA",
  "arizona", "USA",
  "arkansas", "USA",
  "california", "USA",
  "florida", "USA",
  "texas", "USA",
  "new york", "USA",
  "idaho", "USA",
  "alaska", "USA",
  "ohio", "USA",
  "pennsylvania", "USA",
  "michigan", "USA",
  "north carolina", "USA",
  "virginia", "USA",
  "oregon", "USA",
  "washington", "USA",
  "massachusetts", "USA",
  "illinois", "USA",
  "indiana", "USA",
  "iowa", "USA",
  "carolina", "USA",
  "south carolina", "USA",
  "kentucky", "USA",
  "maryland", "USA",
  "mississippi", "USA",
  "missouri", "USA",
  "connecticut", "USA",
  "dakota", "USA",
  "delaware", "USA",
  "louisiana", "USA",
  "new jersey", "USA",
  "new mexico", "USA",
  "oklahoma", "USA",
  "alabama", "USA",
  "maine", "USA",
  "minnesota", "USA",
  "nebraska", "USA",
  "kansas", "USA",
  "western australia", "AUS",
  "south australia", "AUS",
  "victoria", "AUS",
  "tasmania", "AUS",
  "queensland", "AUS",
  "eastern australia", "AUS",
  "southwestern australia", "AUS",
  "south-western australia", "AUS",
  "northern territory", "AUS",
  "northern territory of australia", "AUS",
  # Country variants and corrections
  "usa", "USA",
  "new-zealand", "NZL",
  "brasil", "BRA",
  "burma", "MMR",
  "cameroun", "CMR",
  "french polynesia", "PYF",
  "republic of panama", "PAN",
  "russian federation", "RUS",
  "the peoples republic of china", "CHN",
  "federal republic of germany", "DEU",
  "ksa", "SAU",
  "ontario", "CAN",
  "alberta", "CAN",
  "manitoba", "CAN",
  "quebec", "CAN",
  "canada western canada", "CAN",
  "antarctica", "ATA",
  "antarctic", "ATA",
  "lagotellerie", "ATA",
  "moutonné valley on alexander island", "ATA",
  "east antarctica", "ATA",
  "east continental antarctica", "ATA",
  "south antarctica", "ATA",
  "central transantarctic mountains", "ATA",
  "moutonné valley on alexander", "ATA",
  "transantarctic mountains", "ATA",
  "king george", "ATA",
  "king george island", "ATA",
  "angola", "AGO",
  "jordan", "JOR",
  "maritime antarctica", "ATA",
  "rhynie", "GBR",
  "bermuda", "BMU",
  "bosnia", "BIH",
  "herzegovina", "BIH",
  "newfoundland", "CAN",
  "la réunion", "REU",
  "cote divoire", "CIV",
  "côte divoire", "CIV",
  "yugoslavia", "SRB",
  "bicol", "PHL",
  "southern italy", "ITA",
  "parts of italy", "ITA",
  "dutch", "NLD",
  "east india", "IND",
  "finnish", "FIN",
  "korean", "KOR",
  "northern spain", "ESP",
  "central spain", "ESP",
  "british-columbia", "CAN",
  "brunswick", "CAN",
  "buenos aires", "ARG",
  "canadian", "CAN",
  "chiapas", "MEX",
  "colorado", "USA",
  "cordoba", "ARG",
  "cuneo", "ITA",
  "gujarat", "IND",
  "jalisco", "MEX",
  "kashmir", "IND",
  "paraná", "BRA",
  "patagonia", "ARG",
  "peruvian amazon", "PER",
  "sinaloa", "MEX",
  "southeastern brazil", "BRA",
  "southern france", "FRA",
  "southern morocco", "MAR",
  "southern poland", "POL",
  "veracruz", "MEX",
  "western montana", "USA",
  "western oregon", "USA",
  "akmola", "KAZ",
  "alberta rocky mountains", "CAN",
  "andaman", "IND",
  "apulia", "ITA",
  "baise", "CHN",
  "bangi", "CAF",
  "bisle ghat", "IND",
  "british", "GBR",
  "campina grande", "BRA",
  "cear? state", "BRA",
  "chengde", "CHN",
  "chenzhou", "CHN",
  "chikwawa", "MWI",
  "chilean southern andes", "CHL",
  "cianjur", "IDN",
  "cili country", "CHN",
  "columbia basin", "USA",
  "egyptian", "EGY",
  "french pyrenees", "FRA",
  "gannan", "CHN",
  "german", "DEU",
  "germany berlin", "DEU",
  "guizhou dushan", "CHN",
  "hexi", "CHN",
  "hitachi mine", "JPN",
  "hull", "GBR",
  "inner mengolia", "CHN",
  "inner mongolia of northern china", "CHN",
  "people’s republic of china", "CHN",
  "ningxia", "CHN",
  "central panama", "PAN",
  "central spain", "ESP",
  "hainan island", "CHN",
  "south india", "IND",
  "jammu & kashmir", "IND",
  "korean ecotype", "KOR",
  "lueyang country", "CHN",
  "mala y sia", "MYS",
  "malay", "MYS",
  "min county", "CHN",
  "minqin of gansu", "CHN",
  "minxian", "CHN",
  "monte azul", "BRA",
  "ningxia hui autonomous region of china", "CHN",
  "north-west china", "CHN",
  "north-west tasmania", "AUS",
  "north-western himalaya", "IND",
  "northern china", "CHN",
  "northern finland", "FIN",
  "aland", "FIN",
  "northern germany", "DEU",
  "northern mexico", "MEX",
  "northern pennsylvania", "USA",
  "northwestern himalayas", "IND",
  "panan", "CHN",
  "pauri", "IND",
  "pingjiang", "CHN",
  "qilian mountain", "CHN",
  "qinghai-tibetan plateau", "CHN",
  "qinghai-xizang", "CHN",
  "qinghai-xizang plateau", "CHN",
  "río negro", "ARG",
  "san luis", "ARG",
  "shapotou of ningxia", "CHN",
  "south-east queensland", "AUS",
  "south-eastern england", "GBR",
  "south-west britain", "GBR",
  "south-west china", "CHN",
  "southeastern queensland", "AUS",
  "southern bahia state", "BRA",
  "southern kyushu", "JPN",
  "tatra mountains", "SVK",
  "te anau", "NZL",
  "tibetan autonomous", "CHN",
  "tierra del fuego", "ARG",
  "tongren city", "CHN",
  "wenxian", "CHN",
  "western alps", "ITA",
  "western anatolia", "TUR",
  "western hubei", "CHN",
  "western siberia", "RUS",
  "willamette valley", "USA",
  "xiongan new area", "CHN",
  "yinchuan", "CHN",
  "yinjing", "CHN",
  "yunnan menglian", "CHN",
  "yuqian", "CHN",
  "zhuhai", "CHN",
  "zhuhai city", "CHN",
  "zunyi country", "CHN",
  "continental antarctica", "ATA",
  "coast of india", "IND",
  "county in barinas", "VEN",
  "district udhampur in jammu division", "IND",
  "dongxiang", "CHN",
  "gurbantunggut desert", "CHN",
  "including china", "CHN",
  "india/bangladesh", "IND",
  "india/bangladesh", "BGD",
  "southern iberian", "ESP",
  "southern iberian", "PRT",
  "rkiye", "TUR",
  "tü", "TUR",
  "ind", "IND",
  "greenland", "GRL",
  "iceland", "ISL",
  "mississippi river basin", "USA",
  "svalbard", "NOR",
  "franz josef land", "RUS",
  "new siberian islands", "RUS",
  "novaya zemlya", "RUS",
  "macdonnell ranges", "AUS",
  "brazilian highlands", "BRA",
  "guiana highlands", "GUY",
  "são tomé and príncipe", "STP",
  "canadian arctic archipelago", "CAN",
  "ural mountains", "RUS",
  "severnaya zemlya", "RUS",
  "wrangel island", "RUS",
  "great lakes", "USA",
  "great lakes", "CAN",
  "hudson bay", "CAN",
  "sierra madre oriental", "MEX",
  "sierra madre occidental", "MEX",
  "sierra madre del sur", "MEX",
  "trans-mexican volcanic belt", "MEX",
  "sonoran desert", "USA",
  "sonoran desert", "MEX",
  "mojave desert", "USA",
  "chihuahuan desert", "USA",
  "chihuahuan desert", "MEX",
  "great basin desert", "USA",
  "colorado plateau", "USA",
  "rocky mountains", "USA",
  "rocky mountains", "CAN",
  "appalachian mountains", "USA",
  "appalachian mountains", "CAN",
  "sierra nevada", "USA",
  "cascade range", "USA",
  "cascade range", "CAN",
  "coast ranges", "USA",
  "coast ranges", "CAN",
  "great plains", "USA",
  "great plains", "CAN",
  "central valley", "USA",
  "juan fernández islands", "CHL",
  "desventuradas islands", "CHL",
  "magellanic subpolar forests", "CHL",
  "magellanic subpolar forests", "ARG",
  "valdivian temperate rain forest", "CHL",
  "valdivian temperate rain forest", "ARG",
  "patagonian steppe", "ARG",
  "patagonian steppe", "CHL",
  "pampas", "ARG",
  "pampas", "URY",
  "pampas", "BRA",
  "gran chaco", "ARG",
  "gran chaco", "BOL",
  "gran chaco", "PRY",
  "gran chaco", "BRA",
  "atlantic forest", "BRA",
  "atlantic forest", "ARG",
  "atlantic forest", "PRY",
  "cerrado", "BRA",
  "cerrado", "BOL",
  "cerrado", "PRY",
  "caatinga", "BRA",
  "yungas", "BOL",
  "yungas", "PER",
  "yungas", "ARG",
  "puna", "ARG",
  "puna", "BOL",
  "puna", "CHL",
  "puna", "PER",
  "paramo", "COL",
  "paramo", "ECU",
  "paramo", "PER",
  "paramo", "VEN",
  "atacama", "CHL",
  "maule", "CHL",
  "santiago", "CHL",
  "coquimbo", "CHL",
  "monte", "ARG",
  "espinal", "ARG",
  "tumbes-chocó-magdalena", "COL",
  "tumbes-chocó-magdalena", "ECU",
  "tumbes-chocó-magdalena", "PAN",
  "tumbes-chocó-magdalena", "PER",
  "chocó-darién", "COL",
  "chocó-darién", "PAN",
  "panamanian", "PAN",
  "sino-japanese", "CHN",
  "sino-japanese", "JPN",
  "sundanian", "IDN",
  "sundanian", "MYS",
  "sundanian", "BRN",
  "wallacean", "IDN",
  "philippine", "PHL",
  "sundaland", "IDN",
  "sundaland", "MYS",
  "sundaland", "BRN",
  "sundaland", "SGP",
  "sundaland", "THA",
  "wallacea", "IDN",
  "beringia", "RUS",
  "beringia", "USA",
  "himalayas", "NPL",
  "himalayas", "BTN",
  "himalayas", "IND",
  "himalayas", "CHN",
  "himalayas", "PAK",
  "tibetan plateau", "CHN",
  "kunlun mountains", "CHN",
  "tian shan", "CHN",
  "tian shan", "KAZ",
  "tian shan", "KGZ",
  "tian shan", "UZB",
  "altai mountains", "RUS",
  "altai mountains", "CHN",
  "altai mountains", "MNG",
  "altai mountains", "KAZ",
  "sayan mountains", "MNG",
  "sayan mountains", "RUS",
  "stanovoy range", "RUS",
  "verkhoyansk range", "RUS",
  "chersky range", "RUS",
  "kolyma mountains", "RUS",
  "sikhote-alin", "RUS",
  "zagros mountains", "IRN",
  "zagros mountains", "IRQ",
  "zagros mountains", "TUR",
  "taurus mountains", "TUR",
  "pontic mountains", "TUR",
  "anatolian plateau", "TUR",
  "iranian plateau", "IRN",
  "iranian plateau", "AFG",
  "iranian plateau", "PAK",
  "armenian highlands", "ARM",
  "armenian highlands", "TUR",
  "armenian highlands", "IRN",
  "armenian highlands", "AZE",
  "armenian highlands", "GEO",
  "ethiopian highlands", "ETH",
  "ethiopian highlands", "ERI",
  "drakensberg", "ZAF",
  "drakensberg", "LSO",
  "atlas mountains", "MAR",
  "atlas mountains", "DZA",
  "atlas mountains", "TUN",
  "ahaggar mountains", "DZA",
  "tibesti mountains", "TCD",
  "tibesti mountains", "LBY",
  "guinea highlands", "GIN",
  "guinea highlands", "SLE",
  "guinea highlands", "LBR",
  "guinea highlands", "CIV",
  "cameroon highlands", "CMR",
  "cameroon highlands", "NGA",
  "australian alps", "AUS",
  "great dividing range", "AUS",
  "kimberley", "AUS",
  "hamersley range", "AUS",
  "darling range", "AUS",
  "new guinea highlands", "IDN",
  "new guinea highlands", "PNG",
  "southern alps", "NZL",
  "hawaiian islands", "USA",
  "galapagos islands", "ECU",
  "canary islands", "ESP",
  "azores", "PRT",
  "cape verde", "CPV",
  "maldives", "MDV",
  "chagos archipelago", "IOT",
  "andaman islands", "IND",
  "nicobar islands", "IND",
  "lakshadweep", "IND",
  "new guinea", "IDN",
  "new guinea", "PNG",
  "sakhalin", "RUS",
  "kuril islands", "RUS",
  "aleutian islands", "USA",
  "south georgia and the south sandwich islands", "SGS",
  "bouvet island", "BVT",
  "heard island and mcdonald islands", "HMD",
  "kermadec islands", "NZL",
  "chatham islands", "NZL",
  "auckland islands", "NZL",
  "campbell island", "NZL",
  "antipodes islands", "NZL",
  "bounty islands", "NZL",
  "snares islands", "NZL",
  "macquarie island", "AUS",
  "tonga", "TON",
  "cook islands", "COK",
  "pitcairn islands", "PCN",
  "easter island", "CHL",
  "saint helena, ascension and tristan da cunha", "SHN",
  "andorra", "AND",
  "anguilla", "AIA",
  "armenia", "ARM",
  "aruba", "ABW",
  "br. indian ocean ter.", "IOT",
  "br indian ocean ter", "IOT",
  "british indian ocean", "IOT",
  "british virgin is.", "VGB",
  "cayman is.", "CYM",
  "curaçao", "CUW",
  "dem. rep. korea", "PRK",
  "eq. guinea", "GNQ",
  "fr. s. antarctic lands", "ATF",
  "fr s antarctic lands", "ATF",
  "french s antarctic lands", "ATF",
  "gambia", "GMB",
  "georgia", "GEO",
  "guam", "GUM",
  "guernsey", "GGY",
  "jersey", "JEY",
  "lesotho", "LSO",
  "liechtenstein", "LIE",
  "macao", "MAC",
  "monaco", "MCO",
  "montserrat", "MSR",
  "n. mariana is.", "MNP",
  "norfolk island", "NFK",
  "st-barthélemy", "BLM",
  "st-martin", "MAF",
  "st. pierre and miquelon", "SPM",
  "st. vin. and gren.", "VCT",
  "swaziland", "SWZ",
  "eswatini", "SWZ",
  "turks and caicos is.", "TCA",
  "u.s. virgin is.", "VIR",
  "w. sahara", "ESH",
  "wallis and futuna", "WLF",
  "america", "USA",
  "siberia", "RUS",
  "amazon", "BRA",
  "amazonia", "BRA",
  "bengal", "IND",
  "sundarbans", "IND",
  # French territories (alternate spellings)
  "reunion", "REU",
  "réunion", "REU",
  "sao tome", "STP",
  "sao tome and principe", "STP",
  "st pierre", "SPM",
  "guadeloupe", "GLP",
  "st barthélemy", "BLM",
  "st martin", "MAF",
  "wallis and futuna islands", "WLF",
  "wallis et futuna", "WLF",
  # Central Asian alternate spellings
  "kirghizstan", "KGZ",
  "kirgizia", "KGZ",
  "tadjikistan", "TJK",
  "tadzhikistan", "TJK",
  "tadzhik", "TJK",
  # Other European territories
  "aland islands", "ALA",
  "åland islands", "ALA",
  "åland", "ALA",
  "isle of man", "IMN",
  "channel islands", "GGY",
  "san marino", "SMR",
  # Caribbean variants
  "st lucia", "LCA",
  "st vincent", "VCT",
  "st kitts", "KNA",
  "nevis", "KNA",
  "antigua", "ATG",
  "barbuda", "ATG",
  "turks and caicos", "TCA",
  "curacao", "CUW",
  "sint maarten", "MAF",
  # Antarctic/South Atlantic
  "falkland", "FLK",
  "falklands", "FLK",
  "heard island", "HMD",
  "heard", "HMD",
  "south georgia", "SGS",
  "sandwich islands", "SGS",
  # Asian Pacific territories
  "saipan", "MNP",
  "northern mariana", "MNP",
  "american samoa", "ASM",
  "niue", "NIU",
  "solomon", "SLB",
  "pitcairn", "PCN",
  "norfolk", "NFK",
  "yemen", "YEM",
  "east timor", "TLS",
  "timor leste", "TLS",
  "ukraine", "UKR",
  "dprk", "PRK",
  "west bank", "PSE",
  "gaza", "PSE",
  "gaza strip", "PSE",
  "malta", "MLT",
  "saint helena", "SHN",
  "tristan da cunha", "SHN",
  "faroe islands", "FRO",
  "mascarene", "MUS",
  # Additional US States
  "south dakota", "USA",
  "south florida", "USA",
  "south texas", "USA",
  "central texas", "USA",
  "central indiana", "USA",
  "west virginia", "USA",
  # Chinese Provinces and Cities
  "chongqing", "CHN",
  "henan", "CHN",
  "hubei", "CHN",
  "hunan", "CHN",
  "jiangsu", "CHN",
  "shaanxi", "CHN",
  "shandong", "CHN",
  "tianjin", "CHN",
  "xinjiang uygur autonomous", "CHN",
  "guangxi zhuang autonomous", "CHN",
  "hebei", "CHN",
  "eastern zhejiang", "CHN",
  "northwestern china", "CHN",
  "subtropical china", "CHN",
  "nanjing", "CHN",
  "nanping city", "CHN",
  "shenmu city", "CHN",
  "shihezi", "CHN",
  "huhhot", "CHN",
  "hulun buir", "CHN",
  "hulunbuir", "CHN",
  "jiangpu", "CHN",
  "jingxi county", "CHN",
  "shanxi", "CHN",
  "xishuangbanna", "CHN",
  "east qilian mountain", "CHN",
  "sichuan provinces", "CHN",
  # Indonesian Regions
  "central kalimantan", "IDN",
  "central sulawesi", "IDN",
  "central sumatra", "IDN",
  "south sumatra", "IDN",
  "west java", "IDN",
  "west sumatra", "IDN",
  "north sumatra", "IDN",
  "java island", "IDN",
  "timor island", "IDN",
  # Indian Regions
  "north east india", "IND",
  "north india", "IND",
  "south andaman island", "IND",
  # Other Countries
  "central argentina", "ARG",
  "central germany", "DEU",
  "central mexico", "MEX",
  "north spain", "ESP",
  "west germany", "DEU",
  "west carpathian", "SVK",
  "south finland", "FIN",
  # Island Territories
  "balearic islands", "ESP",
  "gomera island", "ESP",
  "madeira island", "PRT",
  "mascarene islands", "MUS",
  "moorea island", "PYF",
  "south georgia to the leonie islands", "SGS",
  "south shetland islands", "SGS",
  "south shetlands islands", "SGS",
  "spitsbergen island", "NOR",
  # ISO 3166-1 alpha-3 code variants (for matching when extracted as ISO codes)
  # Uppercase variants
  "CHN", "CHN",
  "BRA", "BRA",
  "EGY", "EGY",
  "NER", "NER",
  "CAN", "CAN",
  "IDN", "IDN",
  "ITA", "ITA",
  "AUS", "AUS",
  "THA", "THA",
  "KOR", "KOR",
  "ARG", "ARG",
  "MEX", "MEX",
  "ESP", "ESP",
  "IRN", "IRN",
  "NZL", "NZL",
  "JPN", "JPN",
  "PAK", "PAK",
  "DEU", "DEU",
  "POL", "POL",
  "SAU", "SAU",
  "ZAF", "ZAF",
  "MYS", "MYS",
  "BGD", "BGD",
  "CHL", "CHL",
  "ATA", "ATA",
  "NOR", "NOR",
  "FRA", "FRA",
  "TWN", "TWN",
  "GBR", "GBR",
  "LKA", "LKA",
  "NGA", "NGA",
  "MAR", "MAR",
  "FIN", "FIN",
  "CHE", "CHE",
  "MNG", "MNG",
  "NLD", "NLD",
  "PAN", "PAN",
  "RUS", "RUS",
  "TUR", "TUR",
  "DZA", "DZA",
  "COL", "COL",
  "PRT", "PRT",
  "ECU", "ECU",
  "PHL", "PHL",
  "ROU", "ROU",
  "UKR", "UKR",
  "CMR", "CMR",
  "CRI", "CRI",
  "URY", "URY",
  "KEN", "KEN",
  "PER", "PER",
  "VNM", "VNM",
  "CZE", "CZE",
  "SWE", "SWE",
  "HUN", "HUN",
  "PRI", "PRI",
  "AUT", "AUT",
  "TUN", "TUN",
  "GRC", "GRC",
  "ISR", "ISR",
  "MLI", "MLI",
  "PRY", "PRY",
  "ETH", "ETH",
  "IRQ", "IRQ",
  "DNK", "DNK",
  "GHA", "GHA",
  "SRB", "SRB",
  "NAM", "NAM",
  "SVN", "SVN",
  "UZB", "UZB",
  "VEN", "VEN",
  "HKG", "HKG",
  "OMN", "OMN",
  "GIN", "GIN",
  "HRV", "HRV",
  "GEO", "GEO",
  "LTU", "LTU",
  "SDN", "SDN",
  "SVK", "SVK",
  "TZA", "TZA",
  "BFA", "BFA",
  "BOL", "BOL",
  "CUB", "CUB",
  "EST", "EST",
  "NPL", "NPL",
  "UGA", "UGA",
  "BGR", "BGR",
  "GUF", "GUF",
  "IRL", "IRL",
  "BEL", "BEL",
  "HND", "HND",
  "MDG", "MDG",
  "MNE", "MNE",
  "PNG", "PNG",
  "SGP", "SGP",
  "KAZ", "KAZ",
  "PYF", "PYF",
  "BLR", "BLR",
  "BMU", "BMU",
  # Lowercase variants (most common in extracted data)
  "chn", "CHN",
  "bra", "BRA",
  "egy", "EGY",
  "ner", "NER",
  "can", "CAN",
  "idn", "IDN",
  "ita", "ITA",
  "aus", "AUS",
  "tha", "THA",
  "kor", "KOR",
  "arg", "ARG",
  "mex", "MEX",
  "esp", "ESP",
  "irn", "IRN",
  "nzl", "NZL",
  "jpn", "JPN",
  "pak", "PAK",
  "deu", "DEU",
  "pol", "POL",
  "sau", "SAU",
  "zaf", "ZAF",
  "mys", "MYS",
  "bgd", "BGD",
  "chl", "CHL",
  "ata", "ATA",
  "nor", "NOR",
  "fra", "FRA",
  "twn", "TWN",
  "gbr", "GBR",
  "lka", "LKA",
  "nga", "NGA",
  "mar", "MAR",
  "fin", "FIN",
  "che", "CHE",
  "mng", "MNG",
  "nld", "NLD",
  "pan", "PAN",
  "rus", "RUS",
  "tur", "TUR",
  "dza", "DZA",
  "col", "COL",
  "prt", "PRT",
  "ecu", "ECU",
  "phl", "PHL",
  "rou", "ROU",
  "ukr", "UKR",
  "cmr", "CMR",
  "cri", "CRI",
  "ury", "URY",
  "ken", "KEN",
  "per", "PER",
  "vnm", "VNM",
  "cze", "CZE",
  "swe", "SWE",
  "hun", "HUN",
  "pri", "PRI",
  "aut", "AUT",
  "tun", "TUN",
  "grc", "GRC",
  "isr", "ISR",
  "mli", "MLI",
  "pry", "PRY",
  "eth", "ETH",
  "irq", "IRQ",
  "dnk", "DNK",
  "gha", "GHA",
  "srb", "SRB",
  "nam", "NAM",
  "svn", "SVN",
  "uzb", "UZB",
  "ven", "VEN",
  "hkg", "HKG",
  "omn", "OMN",
  "gin", "GIN",
  "hrv", "HRV",
  "geo", "GEO",
  "ltu", "LTU",
  "sdn", "SDN",
  "svk", "SVK",
  "tza", "TZA",
  "bfa", "BFA",
  "bol", "BOL",
  "cub", "CUB",
  "est", "EST",
  "npl", "NPL",
  "uga", "UGA",
  "bgr", "BGR",
  "guf", "GUF",
  "irl", "IRL",
  "bel", "BEL",
  "hnd", "HND",
  "mdg", "MDG",
  "mne", "MNE",
  "png", "PNG",
  "sgp", "SGP",
  "kaz", "KAZ",
  "pyf", "PYF",
  "blr", "BLR",
  "bmu", "BMU",
  # Additional ISO codes found in unmatched countries (Phase 2)
  # Uppercase variants
  "BRN", "BRN",
  "COG", "COG",
  "GUY", "GUY",
  "LBY", "LBY",
  "MUS", "MUS",
  "NCL", "NCL",
  "REU", "REU",
  "SYR", "SYR",
  "TTO", "TTO",
  "ZWE", "ZWE",
  "AFG", "AFG",
  "AZE", "AZE",
  "ERI", "ERI",
  "GRL", "GRL",
  "ISL", "ISL",
  "JAM", "JAM",
  "JEY", "JEY",
  "JOR", "JOR",
  "LBN", "LBN",
  "LUX", "LUX",
  "LVA", "LVA",
  "MMR", "MMR",
  "QAT", "QAT",
  "TLS", "TLS",
  "YEM", "YEM",
  "ALB", "ALB",
  "ARE", "ARE",
  "BDI", "BDI",
  "BEN", "BEN",
  "BIH", "BIH",
  "BRB", "BRB",
  "BTN", "BTN",
  "BWA", "BWA",
  "CIV", "CIV",
  "COD", "COD",
  "DMA", "DMA",
  "DOM", "DOM",
  "GNB", "GNB",
  "GTM", "GTM",
  "IMN", "IMN",
  "KHM", "KHM",
  "LAO", "LAO",
  "MDA", "MDA",
  "MLT", "MLT",
  "MOZ", "MOZ",
  "MTQ", "MTQ",
  "MWI", "MWI",
  "NIC", "NIC",
  "SEN", "SEN",
  "SGS", "SGS",
  "TCD", "TCD",
  "TGO", "TGO",
  "VUT", "VUT",
  "ZMB", "ZMB",
  # Lowercase variants
  "brn", "BRN",
  "cog", "COG",
  "guy", "GUY",
  "lby", "LBY",
  "mus", "MUS",
  "ncl", "NCL",
  "reu", "REU",
  "syr", "SYR",
  "tto", "TTO",
  "zwe", "ZWE",
  "afg", "AFG",
  "aze", "AZE",
  "eri", "ERI",
  "grl", "GRL",
  "isl", "ISL",
  "jam", "JAM",
  "jey", "JEY",
  "jor", "JOR",
  "lbn", "LBN",
  "lux", "LUX",
  "lva", "LVA",
  "mmr", "MMR",
  "qat", "QAT",
  "tls", "TLS",
  "yem", "YEM",
  "alb", "ALB",
  "are", "ARE",
  "bdi", "BDI",
  "ben", "BEN",
  "bih", "BIH",
  "brb", "BRB",
  "btn", "BTN",
  "bwa", "BWA",
  "civ", "CIV",
  "cod", "COD",
  "dma", "DMA",
  "dom", "DOM",
  "gnb", "GNB",
  "gtm", "GTM",
  "imn", "IMN",
  "khm", "KHM",
  "lao", "LAO",
  "mda", "MDA",
  "mlt", "MLT",
  "moz", "MOZ",
  "mtq", "MTQ",
  "mwi", "MWI",
  "nic", "NIC",
  "sen", "SEN",
  "sgs", "SGS",
  "tcd", "TCD",
  "tgo", "TGO",
  "vut", "VUT",
  "zmb", "ZMB"
) %>%
  distinct(country_clean, .keep_all = TRUE)

# Export the mapping for use in other scripts
# Usage: source("scripts/utils/country_mapping.R")
# Then use: country_iso_mapping
