# BMB 2026-06-17
# Biome-level plots — distribution, country and family heatmaps, and trends over time.

library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(tidyr)
library(forcats)
library(viridis)
library(scales)

source("scripts/05_plotting/theme_utils.R")

# Use the year-enriched file if available, fallback to final
INPUT_FILE <- "data/Ollama_cleaned_synresolved_standardized_year.csv"
if (!file.exists(INPUT_FILE)) {
  INPUT_FILE <- "data/Ollama_cleaned_synresolved_standardized_final.csv"
}

OUTPUT_DIR <- "results/biome_analysis"
if (!dir.exists(OUTPUT_DIR)) {
  dir.create(OUTPUT_DIR, recursive = TRUE, showWarnings = FALSE)
}

cat("Loading data from:", INPUT_FILE, "\n")
df <- read_csv(INPUT_FILE, show_col_types = FALSE)

# --- Load Country Name Lookup ---
COUNTRY_LOOKUP_FILE <- "data/country_enriched_data.csv"
country_lookup <- if (file.exists(COUNTRY_LOOKUP_FILE)) {
  read_csv(COUNTRY_LOOKUP_FILE, show_col_types = FALSE) %>%
    select(iso_a3, country_name) %>%
    distinct(iso_a3, .keep_all = TRUE)
} else {
  warning("Country lookup file not found. Country codes will be used.")
  NULL
}

# --- Load Taxonomy Lookup for Family ---
# This data is generated by `scripts/04_analyses/02_taxonomy.R` and contains
# the official family assignment for each resolved plant species.
TAXONOMY_LOOKUP_FILE <- "results/taxonomy_analysis/top_studied_plant_species.csv"
if (!file.exists(TAXONOMY_LOOKUP_FILE)) {
  stop("Taxonomy lookup file not found! Please run the 04_analyses scripts first.\n  Expected file: ", TAXONOMY_LOOKUP_FILE)
}

taxa_lookup <- read_csv(TAXONOMY_LOOKUP_FILE, show_col_types = FALSE) %>%
  select(canonicalName, family) %>%
  distinct()

# Join family data to the main dataframe.
# We normalize names to lowercase and remove non-alphanumeric characters
# to ensure the join is robust against minor formatting differences.
df <- df %>%
  mutate(join_name = tolower(gsub("[^A-Za-z ]", "", plant_host_resolved)))

taxa_lookup <- taxa_lookup %>%
  mutate(join_name = tolower(gsub("[^A-Za-z ]", "", canonicalName))) %>%
  select(join_name, family) %>%
  distinct(join_name, .keep_all = TRUE) # Ensure one family per name

df <- df %>%
  left_join(taxa_lookup, by = "join_name") %>%
  select(-join_name) # Clean up the temporary join key

# --- Standardize Biomes ---
standardize_biome <- function(x) {
  x <- str_to_lower(x)
  case_when(
    str_detect(x, "forest|forestry|woodland") ~ "Forest",
    str_detect(x, "agriculture|agricultural|field|vineyard|greenhouse|crop|orchard|plantation") ~ "Agriculture/Cultivated",
    str_detect(x, "grassland|meadow|pasture|prairie|steppe") ~ "Grassland/Pasture",
    str_detect(x, "marine|ocean|sea|coral|pelagic|intertidal") ~ "Marine",
    str_detect(x, "desert|arid|semi-arid") ~ "Desert",
    str_detect(x, "mangrove") ~ "Mangrove",
    str_detect(x, "mountain|alpine|montane|highland") ~ "Mountain/Alpine",
    str_detect(x, "tropical|rainforest|jungle") ~ "Tropical/Rainforest",
    str_detect(x, "savanna|shrubland|scrub|bushland|cerrado") ~ "Savanna/Shrubland/Cerrado",
    str_detect(x, "wetland|swamp|marsh|bog|fen") ~ "Wetland",
    str_detect(x, "urban|city|garden|park") ~ "Urban/Garden",
    str_detect(x, "antarctic|arctic|polar|tundra|ice") ~ "Polar/Tundra",
    is.na(x) | x %in% c("na", "n/a", "none", "unknown", "not specified") ~ NA_character_,
    TRUE ~ "Other/Specific" # Keep others as specific or catch-all
  )
}

# Process paper x biome data
paper_biome <- df %>%
  mutate(
    paper_id = as.character(paper_id),
    biome_clean = standardize_biome(as.character(biome))
  ) %>%
  filter(!is.na(paper_id), !is.na(biome_clean), biome_clean != "Other/Specific") %>%
  distinct(paper_id, biome_clean, .keep_all = TRUE)

# Add full country names if lookup is available
if (!is.null(country_lookup)) {
  paper_biome <- paper_biome %>%
    left_join(country_lookup, by = c("country" = "iso_a3"))
}

# 1. Overall Biome Distribution
biome_counts <- paper_biome %>%
  count(biome_clean, name = "study_count", sort = TRUE)

biome_counts_pct <- biome_counts %>%
  mutate(percent = study_count / sum(study_count) * 100)

# ... (existing code for p1 and ggsave) ...

# 2. Biome x Plant Family Heatmap (Top 10 of each)
# ... (existing code for p2 and ggsave) ...

# 3. Biome Research Over Time (if publication_year exists)
# ... (existing code for p3 and ggsave) ...

# 4. Biome x Country Heatmap (Top 10 of each)
# Use country_name if it was successfully joined, otherwise fall back to the country code
country_col_to_use <- if ("country_name" %in% names(paper_biome)) "country_name" else "country"
y_axis_label <- if (country_col_to_use == "country_name") "Country" else "Country (ISO Code)"

top_biomes <- biome_counts %>%
  slice_head(n = 10) %>%
  pull(biome_clean)

top_countries <- paper_biome %>%
  filter(!is.na(.data[[country_col_to_use]])) %>%
  count(.data[[country_col_to_use]], sort = TRUE) %>%
  slice_head(n = 10) %>%
  pull(1)

biome_country <- paper_biome %>%
  filter(biome_clean %in% top_biomes[1:10], .data[[country_col_to_use]] %in% top_countries) %>%
  count(biome_clean, .data[[country_col_to_use]], name = "study_count") %>%
  complete(biome_clean, !!sym(country_col_to_use), fill = list(study_count = 0))

p4 <- ggplot(biome_country, aes(x = biome_clean, y = fct_reorder(.data[[country_col_to_use]], study_count, .fun = sum), fill = study_count)) +
  geom_tile(color = "white") +
  scale_fill_viridis(option = "rocket", name = "Studies", begin = 0.1, direction = -1) +
  theme_endo_bw(base_size = 11) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    title = "Biome Research by Country",
    subtitle = "Geographic distribution of biome-specific studies (top 10 of each)",
    x = "Biome",
    y = y_axis_label
  )

ggsave(file.path(OUTPUT_DIR, "biome_country_heatmap.png"), p4, width = 6.5, height = 5, dpi = 300)

cat("Biome analysis complete. Plots saved to:", OUTPUT_DIR, "\n")
